### PR TITLE
V2.1.0-rc1 (MANDO) - Disabling old Sprout proofs 

### LINKED ISSUE #66: Add founderaddress to gbt
Hi, 

The founder reward amount is listed in getblocktemplate however the current address is not. Can you please add this into the gbt results?

Thanks

### PR DESCRIPTION
**Pull request by MarcelusCH**
**YODA v2.1.0 also advertise Blossom**

A complete change log can be seen here:
https://github.com/MarcelusCH/bitcoinz/blob/v2.1.0/doc/release-notes/release-notes-2.1.0.md

Notable changes

- Blossom block time set to 150s. Advertising new protocol 770009. 
- New consensus roules set at block #865600. Planned upgrade over v2.1.0 to v2.1.2.
- Disabling old Sprout proofs.
- Fake chain detection during initial block download.
- DoS Mitigation: Mempool Size Limit and Random Drop.
- Checkpoint added for the first live BitcoinZ meeting in Rome.
- Fixing some bugs.
- Updated some copyright.
- Updated block height deprecation to 850500 (after first halving).

The Blossom upgrade on *testnet* will occure at block 32600 (around May 5th). 
Many files (and code part) have been purged due to old Sprout proofs disabling.

### CODE REVIEW

**Review by cryptorex — COMMENTED** [review]
https://github.com/btcz/bitcoinz/blob/master/src/version.h#L21

Upcoming consensus changes will probably require us to set the `MIN_PEER_PROTO_VERSION` to `770009` and we will need to have bridge nodes with -2 minimum protocol version to allow crossover consensus during pre-blossom.

Let me know if this diagram makes sense.  Already corrected to include 770007 as node list appears to show this protocol still in place per @MarcelusCH 

image

**Comment by cryptorex** [comment]
Ok @MarcelusCH thanks for your time at today's meeting. 

To clarify, I think we don't need this technique as it appears we have built-in mechanisms, that is properly designated activation heights.  

I will continue to look through the PR over the weekend and into next week.

Anxious to see Blossom activation at block 32600 on testnet :) https://test.explorer.btcz.app

Also anxious to see our 2.0.7 pre-Blossom testnet nodes behavior post-Blossom activation on testnet.  Cheers!

**Review by cryptorex — COMMENTED** [review]
finished reviewing; moving to compilation and testnet testing

**Comment by MarcelusCH** [comment]
This push disable the blossom activation and add "data" field capability.
It should be an pre-release maybe.

**Comment by cryptorex** [comment]
I have compiled and successfully running the node in Ubuntu 20.04.

should we skip wallet builds and pool updates since this is only an RC? (we can update infrastructure ie. explorer nodes)

**Comment by MarcelusCH** [comment]
Hmmm, wait for the wallet build. I will PR a 2.1.0-rc1 also in the java swing wallet. I will add the ability to send raw tx in it with a data field.
Pool's should not be updated yet with this pre-release. 
Maybe we only upgrade the explorer.btcz.app for now ? ... and we waiting a little for the .rocks

**Comment by cryptorex** [comment]
@MarcelusCH yes I agree, so then:

1) PR to 2.1.0-rc1 to swing wallet (I can build and package binaries for this)
2) no pool, wallet systems updates required
3) only apply update to btcz.app insight instance

**Comment by MarcelusCH** [comment]
PR https://github.com/btcz/bitcoinz-wallet/pull/65 done.

**Comment by MarcelusCH** [comment]
Added correct pre-release value: 
Screenshot from 2022-04-30 09-58-55

**Comment by MarcelusCH** [comment]
As our discussion on Discord, I close this PR because we not longer following zcash versions update.  
Instead we only add in our code the functionalities and security update, and we will get our own versioning path.

**Pull request closed without merging**
