### PR TITLE
2.0.8-1

### LINKED ISSUE #71: Debug.log file Flooding (low impact)
By the node version 2.0.7-10 we added the possibility to add an OP code with an Hex encoded string in the transactions that also give an unexpected output format if it is used. This unexpected output format is `OP_RETURN _<HEX-STRING>_ `. 

This was added in the Raw Transaction class: 
https://github.com/btcz/bitcoinz/blob/977cdc0dce3bb62757e1258b5f9e8a349f4fc637/src/rpc/rawtransaction.cpp#L591

An example of the Raw DATA can be found in this transaction : 
https://explorer.btcz.app/tx/b8b29ff7f76e40d01990fad1a8d51d830a66c9f533c3b1768f78fcaf26888ef4

Now, when the Insight option is activated, the node try to find the spent index information about this OP_RETURN code that are not existing as the spent amount is zero (0). And this trigger an error in the `debug.log `file for each Raw DATA. 

Error in the log file for Insight : `ERROR: Unable to get spent index information`
Triggered here: https://github.com/btcz/bitcoinz/blob/977cdc0dce3bb62757e1258b5f9e8a349f4fc637/src/main.cpp#L1641

Also a similar error happen in the wallet functions.
Error for the Wallet functions : `CWalletTx::GetAmounts: Unknown transaction type found, txid <The_TX_ID> `
Triggered here: https://github.com/btcz/bitcoinz/blob/977cdc0dce3bb62757e1258b5f9e8a349f4fc637/src/wallet/wallet.cpp#L2485

**After some time, the log is flooded by this _badly returned_ error information's !**

The solution is to check if the output is encoded as usually, with an `OP_DUP OP_HASH160` scriptPubKey, or with an Raw DATA field with `OP_RETURN `. This should be done before calling the function that trigger the error. A check could also be done just before the error is triggered but I guess this will probably have an affect on the performance.

### PR DESCRIPTION
**Pull request by MarcelusCH**
This commit should solve the issue https://github.com/btcz/bitcoinz/issues/71

### CODE REVIEW

**Comment by MarcelusCH** [comment]
In the wallet class make a test to know if it's an TX_NULL_DATA.
In the main class make a test to know if outputValue is zero (0) so no spent info possible.

**Comment by MarcelusCH** [comment]
Finally I decided to verify about a zero value. But maybe it is more clean the check in the `CSpentIndexValue` structure about the `addressType` instead of `satoshis`.

https://github.com/btcz/bitcoinz/blob/8e85a88dfaa4eb80a70a5c90c17e92381665a06f/src/spentindex.h#L39

**Comment by MarcelusCH** [comment]
Just updated the changes log and the versioning to 2.0.8-1
This node is actually ruining on https://explorer.btcz.app

**Comment by MarcelusCH** [comment]
By verifying if the spent index exist in the block tree, I modified the return error to only if it's an valid address. I guess it's the best way to still get back the error (that should never happen) without trigger the OP_RETURN code.
Not necessary to check for more and it also avoid a `false` return !

```
    // In either case, we need to get more info ...
    if (!pblocktree->ReadSpentIndex(key, value)) {

      // Check if its an OP_RETURN code. GITHUB ISSUE #71
      // Only return error if it's a valid address
      CTxDestination dest = DestFromAddressHash(value.addressType, value.addressHash);
      if (IsValidDestination(dest)) {
        return error("Unable to get spent index information");
      }
    }
```

**Comment by MarcelusCH** [comment]
@cryptorex we could take this base for deprecation update. I tested it on FN wallet, BWS and explorer. But not on mining nodes... will check in mining-pool channel if someone is ready to test it.

**Comment by MarkLTZ** [comment]
Replaced by #99

**Pull request closed without merging**
