### PR TITLE
Add sk.bitcoinz.global seeder

### PR DESCRIPTION
**Pull request by mr-sk**
This pull request is to add a new seeder to the bitcoinz source. 

Host: sk.bitcoinz.global

Code:
```
vSeeds.push_back(CDNSSeedData("1b880b08d89d7056d5b27c0a1ea9fcaca4d7714eb035a066224d7aeba8a001c6.BTCZ", "sk.bitcoinz.global"));
```

Hash:
```
➜  ~ echo -n sk.bitcoinz.global | shasum
8c0e2be5e2947b37d00e7b48020e17ecea796141
```

### CODE REVIEW

**Comment by renuzit** [comment]
Okay, I'll start this. Does anyone have an example of what other projects do in this situation where a seeder is added to the code base? My question has more to do with the security of the network. I do not have a firm understanding of what impact, security wise, that happens when a seed is added, so a good explanation here might help.

**Comment by mr-sk** [comment]
Good point, I can ask/look around and see what other projects are doing. Don't let that hold up the PR, if you don't mind = ]. Your concern is valid though.

**Comment by mr-sk** [comment]
@renuzit Did a little research. A hard coded list (and hoping for the best) is pretty common way to do this. Not sure about the security aspect though.

**Comment by renuzit** [comment]
I'm fine with this change, hopefully who ever has power to merge can merge it.

**Comment by ghost** [comment]
seeder doesn't work

**Pull request closed without merging**
